apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: {{ .Values.minReplicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      nodeSelector:
        app: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          envFrom:
            - configMapRef:
              name: {{ .Values.name }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
            tcpSocket:
              port: {{ .Values.port }}
            httpGet:
              path: /
              port: {{ .Values.port }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
            tcpSocket:
              port: {{ .Values.port }}
            httpGet:
              path: /
              port: {{ .Values.port }}
