apiVersion: v1
kind: ConfigMap
metadata:
  namespace: NAMESPACE
  name: NAME
  labels:
    app: NAME
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  Serilog__WriteTo__1__Args__path: /logs
